name: Stock Alert Bot

on:
  schedule:
    - cron: "45 13 * * 1-5"   # JST 22:45
    - cron: "45 14 * * 1-5"   # JST 23:45
<<<<<<< HEAD
    - cron: "30 15 * * 1-5"   # JST 24:30 (=翌0:30)
    - cron: "15 21 * * 1-5"   # JST 6:15
=======
    - cron: "30 15 * * 1-5"   # JST 00:30
    - cron: "15 21 * * 1-5"   # JST 06:15
>>>>>>> bf27c94
  workflow_dispatch:          # 手動実行も可能

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        run: python webapp.py

